# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  docker:
    - image: circleci/node:latest
  working_directory: ~/project/repo

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
          - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - repo

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn build

workflows:
  version: 2
  install-and-build:
    jobs:
      - install:
          filters:
            branches:
              ignore: gh-pages
      - build:
          requires:
            - install
